# yaml-language-server: $schema=node_modules/@onlyoffice/typedoc-resource/lib/config.json

- name: main
  source:
    owner: onlyoffice
    repo: docspace-sdk-js-declarations
    reference: develop
    path: docspace-sdk-js.json
