baseUrl: https://api.teamlab.info/
legacyBaseUrl: https://legacy-api.teamlab.info/

analytics: false
robots: false

server:
  baseUrl: https://api.teamlab.info/

playground:
  documentEditor:
    documentServerUrl: https://api.docs.teamlab.info/
