baseUrl: https://api.onlyoffice.com/
legacyBaseUrl: https://legacy-api.onlyoffice.com/
storybookUrl: https://storybook.onlyoffice.com/

analytics: true
robots: true

server:
  baseUrl: https://legacy-api.onlyoffice.com/

playground:
  documentEditor:
    documentServerUrl: https://api.docs.onlyoffice.com/
