baseUrl: https://api.onlyoffice.com/
legacyBaseUrl: https://legacy-api.onlyoffice.com/

analytics: true
robots: true

server:
  baseUrl: https://api.teamlab.info/

playground:
  documentEditor:
    documentServerUrl: https://api.docs.teamlab.info/
