name: Audit

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  audit:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2
      env:
        MISE_HTTP_TIMEOUT: 120s
        MISE_VERBOSE: true

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Packages
      run: pnpm build

    - name: Run Linter
      run: pnpm lint

    - name: Run Tests
      run: pnpm test
