name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Packages
      run: pnpm build

    - name: Build Site
      timeout-minutes: 60
      working-directory: site
      run: pnpm build

    # - name: Publish Site
    # Once the content has been built, you can find it in the `./site/dist`
    # directory. Be aware that this directory could contain as many as 5000
    # files. You can tar it to better deliver content to the server.
